apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.2
  http:
    service:
      spec:
        type: LoadBalancer #Adds a External IP
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
