apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.9.2 #Make sure Kibana and Elasticsearch are on the same version.
  http:
    service:
      spec:
        type: LoadBalancer #Adds a External IP
  count: 1
  elasticsearchRef:
    name: elasticsearch
