apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-api-deployment
  labels:
    app: tweet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet-api
  template:
    metadata:
      labels:
        app: tweet-api
    spec:
      containers:
        - name: tweet-api
          image: tweetapplication.azurecr.io/tweet-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tweet-api-service
spec:
  type: LoadBalancer
  selector:
    app: tweet-api
  ports:
    - protocol: TCP
      port: 80
