version: "3.4"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  rabbitmq:
    image: rabbitmq:3-management-alpine

  prometheus:
    image: prom/prometheus

  grafana:
    image: grafana/grafana

  user-api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  tweet-api:
    image: ${DOCKER_REGISTRY-}tweetapi
    build:
      context: .
      dockerfile: Services/Tweet/Tweet.API/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

  tweetapp-ui:
    image: ${DOCKER_REGISTRY-}tweetapp-ui
    build:
      context: .
      dockerfile: Presentation/Dockerfile

volumes:
  elasticsearch-data:
  prometheus_data: {}
  grafana_data: {}
